version:'3.7'

services:
    currency-exchange-service:
        image: in28min/microservices-currency-microservices:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
            - "8000:8000"
        networks:
            - currency-network
        depends_on:
            - naming-server
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka/
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

            
    naming-server:
        image: in28min/microservices-naming-server:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
            - "8761:8761"
        networks:
            - currency-network
            
    currency-conversion:
        image: in28min/microservices-conversion-microservices:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
            - "8100:8100"
        networks:
            - currency-network     
        depends_on:
            - naming-server   
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka/
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

    api-gateway:
        image: in28min/microservices-Eureka-discovery-client:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
            - "8765:8765"
        networks:
            - currency-network     
        depends_on:
            - naming-server   
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka/
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
                 
                 
    zipkin-server:
        image: openzipkin/zipkin:2.23
        mem_limit: 700m
        ports:
            - "9411:9411"
        networks:
            - currency-network     
        
            
networks:
    currency-network: